Pd 2692 workflow engine catch exceptions during step evaluation
box-id/workflow_engine pull request #4
Opened 2024-08-15 12:27 UTC by nemanjabogdanovic

The Scanpage was having issues with invalid workflow actions ([PD-2620](https://box-id.atlassian.net/jira/software/projects/PD/boards/4/backlog?selectedIssue=PD-2620)).

After a deeper dive, I discovered that the WorkflowEngine simply raises an exception and doesn't return anything in case there is a problem in the step details (i.e. invalid entity for the API action), and traced the problem down to the action execution in `eval_step`.

There was already a written down idea of catching these exceptions and wrapping them in WorkflowEngine.Error.
I added some handling for this, as the ones from the API action were already wrapped.

Added a test for this clause too. I also had to adjust existing tests to expect and assert on an error instead of asserting raised exceptions. This shouldn't break any existing usage as nothing was returned anyway.

After implementing this, I updated my local Scanpage setup to use this branch, and it was in fact what was needed to fix the original bug:
<img width="430" alt="image" src="https://github.com/user-attachments/assets/cdb355c9-13ea-4a90-912e-924592814a4f">

2024-08-15 12:43 UTC, mpneuried reviewed
Code wise it looks good to me.
The only concern i do have is the usage inside the batch service.
https://github.com/box-id/service_batch/blob/main/lib/service_batch/batch_operation/task_runner.ex#L76-L79
Here we differ between error tuple responses with a retry and for hard exceptions with a discard message.
So we should mark this one as breaking change by a major version.

A possible solution could be a marker or hint in the workflow error that this is an error that can be retried ... i know not easy to distinguish.

2024-08-15 12:51 UTC, nemanjabogdanovic commented
> Code wise it looks good to me. The only concern i do have is the usage inside the batch service. https://github.com/box-id/service_batch/blob/main/lib/service_batch/batch_operation/task_runner.ex#L76-L79 Here we differ between error tuple responses with a retry and for hard exceptions with a discard message. So we should mark this one as breaking change by a major version.
> 
> A possible solution could be a marker or hint in the workflow error that this is an error that can be retried ... i know not easy to distinguish.

If we're in the territory of breaking changes, perhaps we can expand the returned error to include additional information, e.g.
```
{:error,
   %{
      message: <currently-returned-message>,
      retry: :never
   }
}
```

2024-08-15 12:55 UTC, mpneuried commented
> > Code wise it looks good to me. The only concern i do have is the usage inside the batch service. https://github.com/box-id/service_batch/blob/main/lib/service_batch/batch_operation/task_runner.ex#L76-L79 Here we differ between error tuple responses with a retry and for hard exceptions with a discard message. So we should mark this one as breaking change by a major version.
> > A possible solution could be a marker or hint in the workflow error that this is an error that can be retried ... i know not easy to distinguish.
> 
> If we're in the territory of breaking changes, perhaps we can expand the returned error to include additional information, e.g.
> 
> ```
> {:error,
>    %{
>       message: <currently-returned-message>,
>       retry: :never
>    }
> }
> ```

Sure, that's what i expected.But we shouldn't remove the [Workflow.Error](https://github.com/box-id/workflow_engine/blob/db3983a518fa6cdcd82f496cea8ad876a68ac222/lib/error.ex#L4). We should extend it with the `:retry`.

2024-08-15 13:13 UTC, nemanjabogdanovic commented
> > > Code wise it looks good to me. The only concern i do have is the usage inside the batch service. https://github.com/box-id/service_batch/blob/main/lib/service_batch/batch_operation/task_runner.ex#L76-L79 Here we differ between error tuple responses with a retry and for hard exceptions with a discard message. So we should mark this one as breaking change by a major version.
> > > A possible solution could be a marker or hint in the workflow error that this is an error that can be retried ... i know not easy to distinguish.
> > 
> > 
> > If we're in the territory of breaking changes, perhaps we can expand the returned error to include additional information, e.g.
> > ```
> > {:error,
> >    %{
> >       message: <currently-returned-message>,
> >       retry: :never
> >    }
> > }
> > ```
> 
> Sure, that's what i expected.But we shouldn't remove the [Workflow.Error](https://github.com/box-id/workflow_engine/blob/db3983a518fa6cdcd82f496cea8ad876a68ac222/lib/error.ex#L4). We should extend it with the `:retry`.

The `Exception.message/1` (https://github.com/box-id/workflow_engine/blob/main/lib/workflow_engine.ex#L180) returns a normal error tuple, e.g. `{:error, String}`, instead of a WorkflowEngine.Error.
For example:
```
{:error,
 "ApiAction: BXDK entity \"Asset\" doesn't exist.\n\nInstruction Pointer:\n0: {:action, :api}\n\nStep Details:\n{\n  \"args\": [\n    \"a1234567\",\n    true\n  ],\n  \"entity\": \"asset\",\n  \"operation\": \"audit\",\n  \"result\": {\n    \"as\": \"result\"\n  },\n  \"type\": \"api\"\n}\n"}
```
If we change it to return `{:error, %WorkflowEngine.Error{}}` that might break something else too. Certainly doable, as we already said we're breaking.

2024-08-20 10:22 UTC, iStefo commented
Good catch @mpneuried with the batch service using the returned error type as indicator for hard or soft fail.

The original Idea was to raise `WorkflowEngine.Error` for definitely unrecoverable errors - errors that arise from the way the workflow was built (i.e. it being misconfigured) - and return error tuples for "runtime" type errors that could potentially be fixed by retrying the operation. E.g. the Api action raises errors for unrecoverable conditions, such as an entity module not existing, while returning an error tuple in other situations (request failed...).

So if we decide to wrap the error tuples' reason values in `WorkflowEngine.Error`, we should mark them by adding a new field to the error struct, yes.
I was initially uncomfortable with returning `{:error, Error.t()}` because I thought it was uncommon in elixir, but it turns out that e.g. Jason does it as well: https://hexdocs.pm/jason/Jason.html#decode/2

So discussion should be about how we mark the error as unrecoverable. Suggestions?

2024-08-20 10:47 UTC, mpneuried commented
> So discussion should be about how we mark the error as unrecoverable. Suggestions?

In my opinion this would make sense as the Workflow is or will be used more in the future.
So returning a real Error with the a flag `recoverable` or similar would be my approach.

Based on that we need to do a major version release as it's probably breaking we need to update also the using services: scanpage and batch service.

2024-08-22 12:24 UTC, nemanjabogdanovic commented
Implemented the discussed changes.

Had to adjust tests as well, there are two error tests that I don't really believe should be recoverable. I marked them with the comment:
`# INFO: is this supposed to be recoverable? likely not?`

2024-08-23 10:48 UTC, mpneuried requested changes
LGTM and I answered your questions in the test.

2024-08-23 10:48 UTC, mpneuried commented on test/actions/http_test.exs
> +      # INFO: is this supposed to be recoverable? likely not?
I also thought about this ...
If we are 100% sure that e.g. all 400 errors are not recoverable, but 500 are, then we could set the `:recoverable`.
On the other hand the http can use any http endpoint, so i would stick with recoverable for all HTTP error codes.

2024-08-23 10:48 UTC, mpneuried commented on test/actions/parse_csv_test.exs
> +      # assert error.recoverable == false
This one is probably not recoverable, as it's caused by a invalid configuration

2024-08-23 12:16 UTC, nemanjabogdanovic commented
I figured a more fine-grained selection of recoverable/unrecoverable was needed.
Had to modifiy the parse_csv error reason into a tuple for distinction.

2024-08-23 12:17 UTC, nemanjabogdanovic commented
@iStefo can't select you for re-review, tagging you here

2024-08-26 13:50 UTC, mpneuried approved these changes
I checked out the latest changes ... 

LGTM 👍 

Feel free to merge and create a new major version as the error response is different

2024-08-26 15:32 UTC, merged