PD-2851 Update Req to 0.5
box-id/workflow_engine pull request #7
Opened 2024-11-22 13:32 UTC by nemanjabogdanovic

Not sure if I missed something with the Action setup.

2024-11-22 15:25 UTC, iStefo requested changes
Don't forget about the changelog :)

2024-11-22 15:25 UTC, iStefo commented on mix.exs
> +      "test.dev": ["test.watch --trace"]
Do we need these additional targets?

2024-11-22 15:25 UTC, iStefo commented on lib/actions/http.ex
> +          {:error, Req.TransportError.t()}
Does this type spec work when only req 0.3 is installed? I would assume this leads to problems

2024-11-22 15:25 UTC, iStefo commented on .github_workflows/ci.yml
> +
BXDK is a dependency in dev/test, but checking it out needs the deploy key present. See e.g. batch service pipeline for SSH key setup (do it before the mix install)

2024-11-26 13:55 UTC, mpneuried approved these changes
👍

2024-11-27 19:35 UTC, nemanjabogdanovic commented
@iStefo it's showing that merging is blocked, requiring your approval too (probably because you requested changes)

2024-11-28 06:56 UTC, iStefo approved these changes
👍

2024-11-28 10:29 UTC, merged